language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
# command to run tests
script: nosetests

install:
  - "python setup.py install"
  - pip install coveralls

after_success:
  coveralls

notifications:
  email: true
