language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

install:
  - "pip install ."
  - "pip install coveralls"

# command to run tests
script: nosetests -v

after_success:
  coveralls

notifications:
  email: true
