language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

install:
  - "pip install ."
  - "pip install coverage"
  - "pip install python-coveralls"
  - "pip install nose"

# command to run tests
script: nosetests --with-coverage

after_success: coveralls

notifications:
  email: true
